services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scrapy:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  selenium-parser:
    build:
      context: auto_ria_scraper/selenium
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
